---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: docker installation
    apt:
      name: docker.io
      state: latest
    when: ansible_distribution == "Ubuntu"
    
  - name: docker enable
    service: 
      name: docker
      state: started
      enabled: true
   
  - name: docker build
    docker_image:
      name: containeransible
      build:
        args:
           listen_port: 8080
           
           
                 

